
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments/finalizers
  verbs:
  - update
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments/status
  verbs:
  - get
  - patch
  - update
